name: deploy

on:
  push:
    branches: master

jobs: 
  login: 
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  push:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push images
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          docker-compose build
          docker-compose push

  
